# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='jobs',
            field=models.ManyToManyField(related_name='categories', to='belt_exam_app.Job'),
        ),
    ]
