# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0004_auto_20190720_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='belt_exam_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(related_name='has_jobs', to='belt_exam_app.User'),
        ),
    ]
